# Generated by Django 4.1.3 on 2022-11-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='context',
            new_name='content',
        ),
    ]
